### ISSUE TITLE
ZInstall_host_js9_full raises the error when run on a clean VM

### ISSUE THREAD

**Issue by svs1370** [Jumpscale/bash#75]
The following sequence of commands is executed on a freshly created and updated Ubuntu 16.04 VM:

```
sudo -i
curl https://raw.githubusercontent.com/Jumpscale/bash/development/install.sh?$RANDOM > /tmp/install.sh;bash /tmp/install.sh
source ~/.bashrc
export JS9BRANCH=development
ZInstall_host_js9_full
```

Installation script fails with the following error message:
```
 <<initial output truncated - no warnings or errors so far>>

    Installed /opt/code/github/jumpscale/core9
    Running post install task
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/opt/code/github/jumpscale/core9/setup.py", line 95, in <module>
        'cmds/js9_doc',
      File "/usr/local/lib/python3.4/dist-packages/setuptools/__init__.py", line 129, in setup
        return distutils.core.setup(**attrs)
      File "/usr/lib/python3.4/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/usr/lib/python3.4/distutils/dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "/usr/lib/python3.4/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/opt/code/github/jumpscale/core9/setup.py", line 35, in run
        self.execute(_post_install, (libname, libpath), msg="Running post install task")
      File "/usr/lib/python3.4/distutils/cmd.py", line 336, in execute
        util.execute(func, args, msg, dry_run=self.dry_run)
      File "/usr/lib/python3.4/distutils/util.py", line 301, in execute
        func(*args)
      File "/opt/code/github/jumpscale/core9/setup.py", line 10, in _post_install
        from JumpScale9 import j  # here its still the boostrap JumpScale9
      File "/opt/code/github/jumpscale/core9/JumpScale9/__init__.py", line 148, in <module>
        from .sal.process.SystemProcess import SystemProcess
      File "/opt/code/github/jumpscale/core9/JumpScale9/sal/process/SystemProcess.py", line 253
        async def _read_stream(stream, cb, res):
                ^
    SyntaxError: invalid syntax

    ----------------------------------------
Command "/usr/bin/python3 -c "import setuptools, tokenize;__file__='/opt/code/github/jumpscale/core9/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" develop --no-deps" failed with error code 1 in /opt/code/github/jumpscale/core9/

[-] something went wrong: Could not install core9 of js9
```

**Comment by ahussein** [comment]
which os is running on the vm? It seems that the vm runs python version 3.4 which does not support the aysnc/await syntax.

**Comment by svs1370** [comment]
OS: Ubuntu 16.04 x64

uname -a output: Linux vm-2976 3.13.0-143-generic #192-Ubuntu SMP Tue Feb 27 10:45:36 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

python version installed:
```
dpkg -l python
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name                              Version               Architecture          Description
+++-=================================-=====================-=====================-=======================================================================
ii  python                            2.7.5-5ubuntu3        amd64                 interactive high-level object-oriented language (default version)
```

**Comment by svs1370** [comment]
Here is the full output of the script
[ZInstall_host_js9_full.txt](https://github.com/Jumpscale/bash/files/1928009/ZInstall_host_js9_full.txt)

From the messages I assume that the script attempts to update a bunch of system packages including python.

**Comment by svs1370** [comment]
```
python3 --version
Python 3.4.3
```

**Comment by ahussein** [comment]
I think you have an older version of the os than ubuntu 16.04 the kernel version you mentioned is 3.13.0-143-generic while in 16.04 it comes with 4.13.0-16-generic. Can you please double check ?

**Comment by svs1370** [comment]
```
uname -a
Linux vm-2976 3.13.0-143-generic #192-Ubuntu SMP Tue Feb 27 10:45:36 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by ahussein** [comment]
can you please ping me on telegram @a_hussein, its better than communication here.
